## 예외처리

1️⃣ 예외 (Exception)

- 일반적으로 오류 또는 에러 라는 개념이다

2️⃣ 예외 발생?

- 프로그램이 실행중에 예외가 발생되면 '비정상종료' 된다

3️⃣ 예외처리 (Exception handling)

- 예외가 발생된 이후의 문장부터 정상적으로 수행하도록 처리하는 작업
- '비정상종료' ——————————→ '정상종료'

```python
print("start")
try:
	num = 0
	result = 10/num
	print("결과값:", result)
except ZeroDivisionError as e:
	print("예외발생", e)

print("end(정상종료)")
```

4️⃣ 예외처리 방법

- 예외처리를 담당하는 클래스 제공
    - SyntaxError          : 문법오류
    - NameError           : 참조변수가 없을 때
    - ZeroDivisionError : 0으로 나누었을 때
    - IndexError            : 인덱스 범위 넘어갈 때
    - keyError               : dict에 없는 key 사용시
    - ValueError           : 참조값이 없을 때
    - FileNotFoundError : 파일이 없을 때
    - TypeError           : 타입 불일치
- 단일 except문

```python
'''
try:
	실행코드
	실행코드
except: # 권장 안함
except 예외클래스명 as 별칭 : # 권장
	예외발생시
'''
print("start")
try:
    num = 0
    result = 10/num
    print("결과값:", result)
# except:
except ZeroDivisionError as e:
    print("예외발생", e)

print("end(정상종료)")

```

- 다중 except문

```python
'''
try:
              실행코드1 ==> ZeroDivisionError 발생가능
              실행코드2 ==> FileNotFoundError 발생가능
           except ZeroDivisionError as 별칭: # 권장
              예외발생시 처리코드
           except FileNotFoundError as 별칭: # 권장
              예외발생시 처리코드
           except Exception as 별칭: # 권장
              예외발생시 처리코드
'''
print("start")
try:
    # IndexError
    x = [10, 20]
    # print(x[4])

    # TypeError
    k = [10, 20]
    k2 = (10, 20)
    print(k+k2)
except IndexError as e:
    print("예외발생1", e) # list index out of range
except TypeError as e:
    print("예외발생2", e) # can only concatenate list (not "tuple") to list
except Exception as e:
    print("예외발생3", e)

print("end(정상종료)")

print("클래스의 계층구조보기:", TypeError.mro())
```

- finally문

```python
try:
              실행코드
              실행코드
           except 예외클래스명 as 별칭: # 권장
              예외발생시 처리코드
           finally:
              예외발생 여부와 상관없이 반드시 실행되는 문장
```

5️⃣ 사용자 정의 예외 발생

- 사용자가 강제적으로 예외를 발생시키는 경우

```python
'''
          if 조건:
             raise 예외클래스명("메시지")
             +
         try: ~  except: 문 사용
'''
import random

# print(random.randint(0,2)) # 0 , 1, 2
# help(random.randint)
try:
    result = random.randint(0,2)
    print("난수값:", result)
    if result == 0:
        raise Exception("0이 나와서 예외발생")
except Exception as e:
    print("예외처리 메시지:", e)
print("end")
```